### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by gregdymek** [vlivanov/translate-me#4]
Hi,
How to setup from & to language?
Regards,
Greg

**Comment by vvsevolodovich** [comment]
Open Preferences -> Other Settings -> TranslateMe. Change the comboboxes.

**Comment by ildarkhasanshin** [comment]
in 1.0.0.7 auto language detection does not work when the option *auto-detect* is turned on

**Comment by vvsevolodovich** [comment]
Please, create a separate issue on that and provide examples and (if possible) http requests which demonstrate the issue.
