### ISSUE TITLE
1.0.0.6 endless loading

### ISSUE THREAD

**Issue by ildarkhasanshin** [vlivanov/translate-me#9]
![img-2018-05-03-08-21-51](https://user-images.githubusercontent.com/8765305/39560980-434d47da-4eab-11e8-9794-15c265f3daa0.png)

phpstorm 2018.1.3 eap 181.4892.94

**Comment by vvsevolodovich** [comment]
Should be fixed already. @ildarkhasanshin can you please retest?

**Comment by ildarkhasanshin** [comment]
now ok
